# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Democracy and Elections Centre @ RHUL
email: chris.hanretty@rhul.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  The Democracy and Elections Centre at Royal Holloway brings together researchers interested in electoral behaviour and its consequences, and how elections shape public policy. Here we share some of our blog-posts, papers, and interactive visualizations.
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

plugins:
  - jekyll-scholar
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

scholar:
  source: ./_bibliography
  group_by: year
  group_order: descending
  bibliography: publications.bib
  style: apa-no-doi-no-issue
  bibliography-template: bib

# Conversion
# markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# # Markdown Processing
# kramdown:
#   input: GFM
#   hard_wrap: false
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false
#   parse_block_html: true # default for kramdown is false. This will enable using Markdown links

